language: bash

before_install:
- "wget ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.fna.gz"
- "zcat GRCh38_latest_genomic.fna.gz > GRCh38_latest_genomic.fna"

# Actual tests
script: "./downsampler.sh -d 1000 -f GRCh38_latest_genomic.fna"