language: bash

before_install:
- wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/902/505/505/GCF_902505505.1_FN-B4/GCF_902505505.1_FN-B4_genomic.fna.gz
- zcat GCF_902505505.1_FN-B4_genomic.fna.gz > GCF_902505505.1_FN-B4_genomic.fna

# Actual tests
script: "./downsampler.sh -d 1000 -f GCF_902505505.1_FN-B4_genomic.fna"